### ISSUE TITLE
Make phone number optional

### ISSUE THREAD

**Issue by ghost** [thegameofcode/cipherlayer#4]
Is it possible to have the phone field to be optional in registration process?

 If you are not using Pin Validation feature, maybe this field could also be optional.

**Comment by IGZvictorfierro-zz** [comment]
Sure!

We are going to reduce the config.json file to the minimum as soon as we
could; we know it is a monster file at this moment.

Thank you for your feedback

El lunes, 16 de febrero de 2015, Gustavo Marin notifications@github.com
escribió:

> Is it possible to have the phone field to be optional in registration
> process?
> 
> If you are not using Pin Validation feature, maybe this field could also
> be optional.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thegameofcode/cipherlayer/issues/4.

## 

Thank you.

_Victor Fierro_
[image: Intelygenz] http://www.intelygenz.com/
_t:_  +1 415 299 0867 <%2B1%20415%20747%201571>
_e:_  victor.fierro@intelygenz.com
_w:_  www.intelygenz.com http://www.intelygenz.com/en/
[image: Google Maps] https://goo.gl/maps/DJAkg 350 Townsend St #407, San
Francisco, CA 94107 U.S.A.
[image: Twitter] https://twitter.com/Intelygenz  [image: Google+]
https://www.facebook.com/Intelygenz  [image: Google+]
https://plus.google.com/+Intelygenz-Innovation/  [image: LinkedIn]
https://www.linkedin.com/company/intelygenz  _Intelygenz. If you have a
dream, we can write the code_

**Comment by guumaster** [comment]
I think this feature is already done.
