### ISSUE TITLE
EditorConfig file

### ISSUE THREAD

**Issue by ghost** [thegameofcode/cipherlayer#57]
We should add an [.editorconfig](http://editorconfig.org/) file to simplify the merging process after we set up our IDE of choice with this config.

We are using this `.editorconfig` file on other projects: 

``` editorconfig
# EditorConfig helps developers define and maintain consistent
# coding styles between different editors and IDEs
# editorconfig.org

root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false

[{*.json,*.yml}]
indent_style = space
indent_size = 2

```

I didn't add PR directly so we can choose spaces or tabs and stuffs. What do you guys think?

**Comment by ghost** [comment]
:+1:

**Comment by luismesas** [comment]
:+1: will add that file to the project after the current Pull Request

**Comment by luismesas** [comment]
added on #59
